INSERT INTO users (id, name, age) VALUES (1, "Stacey", 25);
INSERT INTO users (id, name, age) VALUES (2, "Mark", 26);
INSERT INTO users (id, name, age) VALUES (3, "Jacob", 20);
INSERT INTO users (id, name, age) VALUES (4, "Tyler", 30);
INSERT INTO users (id, name, age) VALUES (5, "Selene", 35);
INSERT INTO users (id, name, age) VALUES (6, "Jason", 40);
INSERT INTO users (id, name, age) VALUES (7, "Brad", 22);
INSERT INTO users (id, name, age) VALUES (8, "Chad", 26);
INSERT INTO users (id, name, age) VALUES (9, "Lisa", 28);
INSERT INTO users (id, name, age) VALUES (10, "Brittany", 24);
INSERT INTO users (id, name, age) VALUES (11, "Lauren", 32);
INSERT INTO users (id, name, age) VALUES (12, "Laura", 55);
INSERT INTO users (id, name, age) VALUES (13, "Felicity", 16);
INSERT INTO users (id, name, age) VALUES (14, "Josh", 4);
INSERT INTO users (id, name, age) VALUES (15, "Steve", 45);
INSERT INTO users (id, name, age) VALUES (16, "Kevin", 50);
INSERT INTO users (id, name, age) VALUES (17, "Audrey", 35);
INSERT INTO users (id, name, age) VALUES (18, "Emily", 21);
INSERT INTO users (id, name, age) VALUES (19, "Joanna", 33);
INSERT INTO users (id, name, age) VALUES (20, "Nicki", 36);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES (1, "First", 250000, 01/01/2019, 12/01/2019);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES (2, "Second", 3000, 03/23/2019, 12/01/2019);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES (3, "Third", 278000, 07/24/2019, 09/30/2019);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES (4, "Fourth", 100000, 01/05/2019, 12/01/2019);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES (5, "Fifth", 2000000, 10/04/2019, 12/01/2019);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES (6, "Sixth", 120000, 01/30/2019, 12/01/2019);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES (7, "Seventh", 350000, 09/17/2019, 12/01/2019);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES (8, "Eigth", 20000000, 12/26/2019, 12/30/2019);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES (9, "Ninth", 50000000, 01/01/2019, 12/23/2019);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES (10, "Tenth", 100000000, 01/17/2019, 9/05/2019);

INSERT INTO pledges (id, amount, user_id, project_id) VALUES (1, 100, "user_1", "project_1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (2, 100, "user_2", "project_1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (3, 100, "user_3", "project_1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (4, 100, "user_4", "project_1");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (5, 100, "user_5", "project_2");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (6, 100, "user_6", "project_3");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (7, 100, "user_7", "project_4");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (8, 100, "user_8", "project_5");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (9, 100, "user_9", "project_6");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (10, 100, "user_10", "project_6");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (11, 100, "user_11", "project_6");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (12, 100, "user_12", "project_7");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (13, 100, "user_13", "project_7");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (14, 100, "user_14", "project_7");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (15, 100, "user_15", "project_8");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (16, 100, "user_16", "project_8");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (17, 100, "user_17", "project_8");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (18, 100, "user_18", "project_9");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (19, 100, "user_19", "project_9");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (20, 100, "user_20", "project_9");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (21, 100, "user_21", "project_9");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (22, 100, "user_22", "project_9");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (23, 100, "user_23", "project_9");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (24, 100, "user_24", "project_10");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (25, 100, "user_25", "project_10");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (26, 100, "user_26", "project_10");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (27, 100, "user_27", "project_10");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (28, 100, "user_28", "project_10");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (29, 100, "user_29", "project_10");
INSERT INTO pledges (id, amount, user_id, project_id) VALUES (30, 100, "user_30", "project_10");
